### ISSUE TITLE
Use composer

### ISSUE THREAD

**Issue by ahoiroman** [viruzx/Sitemap-Generator-Crawler#11]
It would be great if I could require this using composer.

**Comment by vezaynk** [comment]
I have never worked with composer but I know what a dependency manager is. This is definitely not something I want to implement into the core file.

The "killer feature" of this sitemap generator is how easy it is to work with - download, change settings, upload and run. Composer complicates that.

To develop on composer, this isn't a package. It isn't a class that you require and call later on. This a stand-alone executable.

If your website implements a midly complex routing scheme, it seems more logical to just copy-paste it into the revelant part of your code.

With all that said, I am still open to an implementation of it as long as it will be in a separate repository (unless if I get a very compelling argument to do otherwise).

**Comment by vezaynk** [comment]
Going to close this issue. If anybody got an argument, feel free to re-open this issue.

**Comment by akiraz2** [comment]
В общем, покатался я по issue & PR и понял что владельцу этого замечательного скрипта не хочется оформлять в виде пакета Composer.
Могу я использовать ваш скрипт чтобы сделать полноценный пакет и потом сделать обертку для своего php-фреймворка Yii2? добавите потом в описание проекта ссылку на мой репозиторий?
