### ISSUE TITLE
only creating one URL where I have 700+

### ISSUE THREAD

**Issue by tejalbaria5** [viruzx/Sitemap-Generator-Crawler#85]
[+] Sitemap has been generated in 1.56 secondsand saved to sitemap.xml
[+] Scanned a total of 1 pages and indexed 0 pages.
[+] Operation Completed

I get this msg when tried to load the script ..

I have 700 + URL on site only fetching 1 URL

**Comment by Remitur** [comment]
What's the URL of the page being indexed?

**Comment by vezaynk** [comment]
Assuming you correctly pointed the script to your website (without mixing up http for https, typos, etc), I have most often seen the issue to be related to SSL, exclusively on windows.

The fix is (possibly) to adjust [this line](https://github.com/knyzorg/Sitemap-Generator-Crawler/blob/master/sitemap.config.php#L50)

from `$curl_validate_certificate = true;` to `$curl_validate_certificate = false;`

Hope this helps.

**Comment by websmartcom** [comment]
Anton is controlling the calls to mirror if this is related to that. Please
explain and advise.

**Comment by vezaynk** [comment]
@websmartcom, I don't know who/what Anton is.

**Comment by websmartcom** [comment]
I apologize. I thought this was in relation to another project we are
working on.

**Comment by vezaynk** [comment]
@tejalbaria5, is this still an issue?

**Comment by vezaynk** [comment]
Closing due to non-activity
