### ISSUE TITLE
Reports empty error after finishing 

### ISSUE THREAD

**Issue by mylselgan** [viruzx/Sitemap-Generator-Crawler#89]
Previously this script worked well on my site (with more than 12000 urls). but from yesterday onwards it is not creating sitemap.xml file after finishing. After running for more than 3 hours it just ends with "Error". I executed the script on command line.

```
 [+] Added: https://mysite.com/finalurl
 [+] Found xmllint, pretty-printing sitemap
Error: 
```
Please guide me in the right way to fix this issue.

**Comment by vezaynk** [comment]
Looks like `xmllint` is failing for you.

Try to find the temporary file its working with and post it.

Remove this if block, see if it helps: https://github.com/knyzorg/Sitemap-Generator-Crawler/blob/41731c550bcc9542afc3a92ee111ac5d3407d16e/sitemap.php#L107

I have a suspicion that the script is outputting invalid xml for some reason. and xmllint is blowing up because of it.
